local monarch = require "monarch.monarch"
local global_constants = require("rendercam.global_constants")

function init(self)
    msg.post(".", "acquire_input_focus")
    local position = vmath.vector4(0, 1000, -50, 0)
    global_constants.set("light", position)
end

function final(self)
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
end

function on_reload(self)
end
