local monarch = require "monarch.monarch"

function init(self)
    msg.post(".", "acquire_input_focus")
end

function final(self)
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
    if monarch.is_busy() then return false end
    
    if action.released then
        monarch.back()
    end
end

function on_reload(self)
end
